import {
  FamilyUnit,
  FamilyMember,
  FollowUpTask,
  SurveyResponse,
  ChildVaccinationRecord,
  AshaMeetingRecord,
} from '../types/storage';

/**
 * Complete 24-Household Matrix (3 * 8 Grid)
 * Fully filled colors:
 * - 7days (Red): 1, 6, 12, 19
 * - 15days (Pink): 2, 7, 14, 21
 * - 30days (Yellow): 3, 9, 16, 23
 * - visited (Green): 4, 8, 11, 15, 18, 22
 * - noData (Gray): 5, 10, 13, 17, 20, 24
 */
export const SEED_FAMILIES: FamilyUnit[] = [
  {
    id: 'f001-0000-0000-0001',
    sequentialNumber: 1,
    houseNumber: 1,
    headName: 'Satish Chandra',
    headDob: '12/05/1982',
    primaryPhone: '9876500001',
    villageName: 'Chandpur',
    visitIntervalDays: 7,
    nextVisitDate: '7 days (Urgent)',
    lastVisitedAt: '10 Aug 2025',
    ashaWorkerPhone: '9876543210',
    status: '7days',
    totalMembers: 4,
    hasPregnancy: true,
    hasDisease: false,
    hasChild: true,
    toiletType: 'Septic Tank',
    waterSource: 'Handpump',
    bplCard: false,
    religion: 'Hindu',
    casteCategory: 'OBC',
    markedForHomeVisit: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f002-0000-0000-0002',
    sequentialNumber: 2,
    houseNumber: 2,
    headName: 'Priya Yadav',
    headDob: '05/11/1988',
    primaryPhone: '9876500002',
    villageName: 'Chandpur',
    visitIntervalDays: 15,
    nextVisitDate: '15 days (Due)',
    lastVisitedAt: '12 Aug 2025',
    ashaWorkerPhone: '9876543210',
    status: '15days',
    totalMembers: 5,
    hasPregnancy: true,
    hasDisease: false,
    hasChild: true,
    toiletType: 'Septic Tank',
    waterSource: 'India Mark-II',
    bplCard: true,
    religion: 'Hindu',
    casteCategory: 'OBC',
    markedForHomeVisit: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f003-0000-0000-0003',
    sequentialNumber: 3,
    houseNumber: 3,
    headName: 'Kailash Patil',
    headDob: '20/03/1975',
    primaryPhone: '9876500003',
    villageName: 'Chandpur',
    visitIntervalDays: 30,
    nextVisitDate: '30 days',
    lastVisitedAt: '15 Aug 2025',
    ashaWorkerPhone: '9876543210',
    status: '30days',
    totalMembers: 3,
    hasPregnancy: false,
    hasDisease: true,
    hasChild: false,
    toiletType: 'Soak Pit',
    waterSource: 'Tap Water',
    bplCard: false,
    religion: 'Hindu',
    casteCategory: 'General',
    markedForHomeVisit: false,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f004-0000-0000-0004',
    sequentialNumber: 4,
    houseNumber: 4,
    headName: 'Ramesh Yadav',
    headDob: '18/09/1990',
    primaryPhone: '9876500004',
    villageName: 'Chandpur',
    visitIntervalDays: null,
    nextVisitDate: 'Visited',
    lastVisitedAt: '20 Aug 2025',
    ashaWorkerPhone: '9876543210',
    status: 'visited',
    totalMembers: 6,
    hasPregnancy: false,
    hasDisease: false,
    hasChild: true,
    toiletType: 'Septic Tank',
    waterSource: 'Handpump',
    bplCard: true,
    religion: 'Hindu',
    casteCategory: 'OBC',
    markedForHomeVisit: false,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f005-0000-0000-0005',
    sequentialNumber: 5,
    houseNumber: 5,
    headName: 'Farooq Khan',
    headDob: '10/01/1985',
    primaryPhone: '9876500005',
    villageName: 'Chandpur',
    visitIntervalDays: null,
    nextVisitDate: 'No data',
    lastVisitedAt: '05 Aug 2025',
    ashaWorkerPhone: '9876543210',
    status: 'noData',
    totalMembers: 2,
    hasPregnancy: false,
    hasDisease: false,
    hasChild: false,
    toiletType: 'Soak Pit',
    waterSource: 'Tap Water',
    bplCard: false,
    religion: 'Muslim',
    casteCategory: 'General',
    markedForHomeVisit: false,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f006-0000-0000-0006',
    sequentialNumber: 6,
    houseNumber: 6,
    headName: 'Shanti Devi',
    headDob: '25/07/1968',
    primaryPhone: '9876500006',
    villageName: 'Chandpur',
    visitIntervalDays: 7,
    nextVisitDate: '7 days (Urgent)',
    lastVisitedAt: '08 Aug 2025',
    ashaWorkerPhone: '9876543210',
    status: '7days',
    totalMembers: 4,
    hasPregnancy: false,
    hasDisease: true, // Oral Cancer NCD
    hasChild: false,
    toiletType: 'Septic Tank',
    waterSource: 'India Mark-II',
    bplCard: true,
    religion: 'Hindu',
    casteCategory: 'SC',
    markedForHomeVisit: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f007-0000-0000-0007',
    sequentialNumber: 7,
    houseNumber: 7,
    headName: 'Meena Kumari',
    headDob: '30/12/1995',
    primaryPhone: '9876500007',
    villageName: 'Chandpur',
    visitIntervalDays: 15,
    nextVisitDate: '15 days',
    lastVisitedAt: '14 Aug 2025',
    ashaWorkerPhone: '9876543210',
    status: '15days',
    totalMembers: 3,
    hasPregnancy: true,
    hasDisease: false,
    hasChild: false,
    toiletType: 'Septic Tank',
    waterSource: 'Handpump',
    bplCard: false,
    religion: 'Hindu',
    casteCategory: 'OBC',
    markedForHomeVisit: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f008-0000-0000-0008',
    sequentialNumber: 8,
    houseNumber: 8,
    headName: 'Vikram Joshi',
    headDob: '14/02/1983',
    primaryPhone: '9876500008',
    villageName: 'Chandpur',
    visitIntervalDays: null,
    nextVisitDate: 'Visited',
    lastVisitedAt: '21 Aug 2025',
    ashaWorkerPhone: '9876543210',
    status: 'visited',
    totalMembers: 4,
    hasPregnancy: false,
    hasDisease: false,
    hasChild: true,
    toiletType: 'Septic Tank',
    waterSource: 'Tap Water',
    bplCard: false,
    religion: 'Hindu',
    casteCategory: 'General',
    markedForHomeVisit: false,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f009-0000-0000-0009',
    sequentialNumber: 9,
    houseNumber: 9,
    headName: 'Sanjay Mishra',
    headDob: '09/06/1979',
    primaryPhone: '9876500009',
    villageName: 'Chandpur',
    visitIntervalDays: 30,
    nextVisitDate: '30 days',
    lastVisitedAt: '16 Aug 2025',
    ashaWorkerPhone: '9876543210',
    status: '30days',
    totalMembers: 5,
    hasPregnancy: false,
    hasDisease: true,
    hasChild: false,
    toiletType: 'Septic Tank',
    waterSource: 'Handpump',
    bplCard: false,
    religion: 'Hindu',
    casteCategory: 'General',
    markedForHomeVisit: false,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f010-0000-0000-0010',
    sequentialNumber: 10,
    houseNumber: 10,
    headName: 'Gurpreet Singh',
    headDob: '22/04/1986',
    primaryPhone: '9876500010',
    villageName: 'Chandpur',
    visitIntervalDays: null,
    nextVisitDate: 'No data',
    lastVisitedAt: null,
    ashaWorkerPhone: '9876543210',
    status: 'noData',
    totalMembers: 4,
    hasPregnancy: false,
    hasDisease: false,
    hasChild: true,
    toiletType: 'Septic Tank',
    waterSource: 'Tap Water',
    bplCard: false,
    religion: 'Sikh',
    casteCategory: 'General',
    markedForHomeVisit: false,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f011-0000-0000-0011',
    sequentialNumber: 11,
    houseNumber: 11,
    headName: 'Anil Gupta',
    headDob: '11/11/1991',
    primaryPhone: '9876500011',
    villageName: 'Chandpur',
    visitIntervalDays: null,
    nextVisitDate: 'Visited',
    lastVisitedAt: '19 Aug 2025',
    ashaWorkerPhone: '9876543210',
    status: 'visited',
    totalMembers: 3,
    hasPregnancy: false,
    hasDisease: false,
    hasChild: false,
    toiletType: 'Septic Tank',
    waterSource: 'Handpump',
    bplCard: false,
    religion: 'Hindu',
    casteCategory: 'General',
    markedForHomeVisit: false,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f012-0000-0000-0012',
    sequentialNumber: 12,
    houseNumber: 12,
    headName: 'Verma',
    headDob: '14/10/1989',
    primaryPhone: '9876500012',
    villageName: 'Chandpur',
    visitIntervalDays: 7,
    nextVisitDate: '7 days (Urgent)',
    lastVisitedAt: '12 Aug 2025',
    ashaWorkerPhone: '9876543210',
    status: '7days',
    totalMembers: 5,
    hasPregnancy: true,
    hasDisease: true,
    hasChild: true,
    toiletType: 'Septic Tank',
    waterSource: 'Handpump',
    bplCard: true,
    religion: 'Hindu',
    casteCategory: 'OBC',
    markedForHomeVisit: true,
    updatedAt: new Date().toISOString(),
  },
  // Households 13 to 24 (completing 3 * 8 Grid = 24 Cells)
  {
    id: 'f013-0000-0000-0013',
    sequentialNumber: 13,
    houseNumber: 13,
    headName: 'Deepak Maurya',
    headDob: '03/07/1984',
    primaryPhone: '9876500013',
    villageName: 'Chandpur',
    visitIntervalDays: null,
    nextVisitDate: 'No data',
    lastVisitedAt: null,
    ashaWorkerPhone: '9876543210',
    status: 'noData',
    totalMembers: 3,
    hasPregnancy: false,
    hasDisease: false,
    hasChild: false,
    toiletType: 'Open Defecation',
    waterSource: 'Well',
    bplCard: true,
    religion: 'Hindu',
    casteCategory: 'OBC',
    markedForHomeVisit: false,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f014-0000-0000-0014',
    sequentialNumber: 14,
    houseNumber: 14,
    headName: 'Naresh Patel',
    headDob: '28/05/1992',
    primaryPhone: '9876500014',
    villageName: 'Chandpur',
    visitIntervalDays: 15,
    nextVisitDate: '15 days',
    lastVisitedAt: '13 Aug 2025',
    ashaWorkerPhone: '9876543210',
    status: '15days',
    totalMembers: 4,
    hasPregnancy: false,
    hasDisease: false,
    hasChild: true, // Aarav Patel immunization
    toiletType: 'Septic Tank',
    waterSource: 'India Mark-II',
    bplCard: false,
    religion: 'Hindu',
    casteCategory: 'OBC',
    markedForHomeVisit: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f015-0000-0000-0015',
    sequentialNumber: 15,
    houseNumber: 15,
    headName: 'Suresh Chauhan',
    headDob: '17/08/1987',
    primaryPhone: '9876500015',
    villageName: 'Chandpur',
    visitIntervalDays: null,
    nextVisitDate: 'Visited',
    lastVisitedAt: '22 Aug 2025',
    ashaWorkerPhone: '9876543210',
    status: 'visited',
    totalMembers: 5,
    hasPregnancy: false,
    hasDisease: false,
    hasChild: true,
    toiletType: 'Septic Tank',
    waterSource: 'Tap Water',
    bplCard: false,
    religion: 'Hindu',
    casteCategory: 'General',
    markedForHomeVisit: false,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f016-0000-0000-0016',
    sequentialNumber: 16,
    houseNumber: 16,
    headName: 'Harish Rawat',
    headDob: '05/01/1978',
    primaryPhone: '9876500016',
    villageName: 'Chandpur',
    visitIntervalDays: 30,
    nextVisitDate: '30 days',
    lastVisitedAt: '18 Aug 2025',
    ashaWorkerPhone: '9876543210',
    status: '30days',
    totalMembers: 4,
    hasPregnancy: false,
    hasDisease: true, // Diabetes
    hasChild: false,
    toiletType: 'Soak Pit',
    waterSource: 'Handpump',
    bplCard: true,
    religion: 'Hindu',
    casteCategory: 'ST',
    markedForHomeVisit: false,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f017-0000-0000-0017',
    sequentialNumber: 17,
    houseNumber: 17,
    headName: 'Mohd. Salim',
    headDob: '19/09/1980',
    primaryPhone: '9876500017',
    villageName: 'Chandpur',
    visitIntervalDays: null,
    nextVisitDate: 'No data',
    lastVisitedAt: null,
    ashaWorkerPhone: '9876543210',
    status: 'noData',
    totalMembers: 3,
    hasPregnancy: false,
    hasDisease: false,
    hasChild: false,
    toiletType: 'Septic Tank',
    waterSource: 'Tap Water',
    bplCard: false,
    religion: 'Muslim',
    casteCategory: 'OBC',
    markedForHomeVisit: false,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f018-0000-0000-0018',
    sequentialNumber: 18,
    houseNumber: 18,
    headName: 'Santosh Paswan',
    headDob: '12/12/1989',
    primaryPhone: '9876500018',
    villageName: 'Chandpur',
    visitIntervalDays: null,
    nextVisitDate: 'Visited',
    lastVisitedAt: '23 Aug 2025',
    ashaWorkerPhone: '9876543210',
    status: 'visited',
    totalMembers: 5,
    hasPregnancy: false,
    hasDisease: false,
    hasChild: true,
    toiletType: 'Soak Pit',
    waterSource: 'India Mark-II',
    bplCard: true,
    religion: 'Hindu',
    casteCategory: 'SC',
    markedForHomeVisit: false,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f019-0000-0000-0019',
    sequentialNumber: 19,
    houseNumber: 19,
    headName: 'Mamta Devi',
    headDob: '24/06/1998',
    primaryPhone: '9876500019',
    villageName: 'Chandpur',
    visitIntervalDays: 7,
    nextVisitDate: '7 days (Urgent)',
    lastVisitedAt: '11 Aug 2025',
    ashaWorkerPhone: '9876543210',
    status: '7days',
    totalMembers: 3,
    hasPregnancy: true, // 3rd trimester ANC
    hasDisease: false,
    hasChild: false,
    toiletType: 'Septic Tank',
    waterSource: 'Handpump',
    bplCard: true,
    religion: 'Hindu',
    casteCategory: 'OBC',
    markedForHomeVisit: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f020-0000-0000-0020',
    sequentialNumber: 20,
    houseNumber: 20,
    headName: 'Joseph D’Souza',
    headDob: '15/03/1985',
    primaryPhone: '9876500020',
    villageName: 'Chandpur',
    visitIntervalDays: null,
    nextVisitDate: 'No data',
    lastVisitedAt: null,
    ashaWorkerPhone: '9876543210',
    status: 'noData',
    totalMembers: 2,
    hasPregnancy: false,
    hasDisease: false,
    hasChild: false,
    toiletType: 'Septic Tank',
    waterSource: 'Tap Water',
    bplCard: false,
    religion: 'Christian',
    casteCategory: 'General',
    markedForHomeVisit: false,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f021-0000-0000-0021',
    sequentialNumber: 21,
    houseNumber: 21,
    headName: 'Vijay Tiwari',
    headDob: '30/10/1981',
    primaryPhone: '9876500021',
    villageName: 'Chandpur',
    visitIntervalDays: 15,
    nextVisitDate: '15 days',
    lastVisitedAt: '15 Aug 2025',
    ashaWorkerPhone: '9876543210',
    status: '15days',
    totalMembers: 4,
    hasPregnancy: false,
    hasDisease: true, // Breast cancer follow-up in family
    hasChild: false,
    toiletType: 'Septic Tank',
    waterSource: 'Handpump',
    bplCard: false,
    religion: 'Hindu',
    casteCategory: 'General',
    markedForHomeVisit: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f022-0000-0000-0022',
    sequentialNumber: 22,
    houseNumber: 22,
    headName: 'Govind Ram',
    headDob: '08/08/1972',
    primaryPhone: '9876500022',
    villageName: 'Chandpur',
    visitIntervalDays: null,
    nextVisitDate: 'Visited',
    lastVisitedAt: '24 Aug 2025',
    ashaWorkerPhone: '9876543210',
    status: 'visited',
    totalMembers: 6,
    hasPregnancy: false,
    hasDisease: false,
    hasChild: true,
    toiletType: 'Soak Pit',
    waterSource: 'India Mark-II',
    bplCard: true,
    religion: 'Hindu',
    casteCategory: 'SC',
    markedForHomeVisit: false,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f023-0000-0000-0023',
    sequentialNumber: 23,
    houseNumber: 23,
    headName: 'Manohar Lal',
    headDob: '14/04/1976',
    primaryPhone: '9876500023',
    villageName: 'Chandpur',
    visitIntervalDays: 30,
    nextVisitDate: '30 days',
    lastVisitedAt: '17 Aug 2025',
    ashaWorkerPhone: '9876543210',
    status: '30days',
    totalMembers: 4,
    hasPregnancy: false,
    hasDisease: false,
    hasChild: true,
    toiletType: 'Septic Tank',
    waterSource: 'Tap Water',
    bplCard: false,
    religion: 'Hindu',
    casteCategory: 'OBC',
    markedForHomeVisit: false,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'f024-0000-0000-0024',
    sequentialNumber: 24,
    houseNumber: 24,
    headName: 'Brijesh Pandey',
    headDob: '21/11/1988',
    primaryPhone: '9876500024',
    villageName: 'Chandpur',
    visitIntervalDays: null,
    nextVisitDate: 'No data',
    lastVisitedAt: null,
    ashaWorkerPhone: '9876543210',
    status: 'noData',
    totalMembers: 3,
    hasPregnancy: false,
    hasDisease: false,
    hasChild: false,
    toiletType: 'Septic Tank',
    waterSource: 'Handpump',
    bplCard: false,
    religion: 'Hindu',
    casteCategory: 'General',
    markedForHomeVisit: false,
    updatedAt: new Date().toISOString(),
  },
];

/**
 * Official Gram Survey Members Registry
 */
export const SEED_MEMBERS: FamilyMember[] = [
  // House 1: Satish Chandra Household
  {
    id: 'm001-0000-0000-0101',
    familyUnitId: 'f001-0000-0000-0001',
    name: 'Satish Chandra',
    initials: 'SC',
    dob: '12/05/1982',
    age: 43,
    gender: 'Male',
    relationship: 'Self',
    phone: '9876500001',
    maritalStatus: 'Married',
    education: 'Middle',
    isAbhaLinked: true,
    isPregnant: false,
    hasChronicCondition: false,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'm001-0000-0000-0102',
    familyUnitId: 'f001-0000-0000-0001',
    name: 'Rajna Devi',
    initials: 'RD',
    dob: '18/08/1986',
    age: 39,
    gender: 'Female',
    relationship: 'Wife',
    phone: '9876500001',
    fatherOrHusbandName: 'Satish Chandra',
    maritalStatus: 'Married',
    education: 'Primary',
    isAbhaLinked: true,
    isPregnant: true,
    expectedDeliveryDate: '15/11/2025',
    isHrp: true,
    hasChronicCondition: false,
    lastSurveyDate: '10 Aug 2025',
    followUpDueDate: '17 Aug 2025',
    followUpReason: 'ANC 2nd Checkup',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'm001-0000-0000-0103',
    familyUnitId: 'f001-0000-0000-0001',
    name: 'Khushbu Kumari',
    initials: 'KK',
    dob: '14/02/2012',
    age: 13,
    gender: 'Female',
    relationship: 'Daughter',
    fatherOrHusbandName: 'Satish Chandra',
    maritalStatus: 'Unmarried',
    education: 'Middle',
    isAbhaLinked: false,
    isPregnant: false,
    hasChronicCondition: false,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'm001-0000-0000-0104',
    familyUnitId: 'f001-0000-0000-0001',
    name: 'Nilesh Kumar',
    initials: 'NK',
    dob: '20/11/2023',
    age: 1,
    gender: 'Male',
    relationship: 'Son',
    fatherOrHusbandName: 'Satish Chandra',
    isChild: true,
    isAbhaLinked: false,
    isPregnant: false,
    hasChronicCondition: false,
    updatedAt: new Date().toISOString(),
  },

  // House 12: Verma Family (ANC 1, ANC 2, Hypertension, Children)
  {
    id: 'm001-0000-0000-0001',
    familyUnitId: 'f012-0000-0000-0012',
    name: 'Suman Verma',
    initials: 'SV',
    dob: '12/04/1997',
    age: 28,
    gender: 'Female',
    relationship: 'Wife',
    fatherOrHusbandName: 'Rajesh Verma',
    phone: '9876543211',
    maritalStatus: 'Married',
    education: 'High School',
    isAbhaLinked: true,
    abhaNumber: '14-1234-5678-9012',
    isPregnant: true,
    expectedDeliveryDate: '20/10/2025',
    isHrp: true, // High Risk Pregnancy
    hasChronicCondition: false,
    lastSurveyDate: '12 Aug 2025',
    followUpDueDate: '19 Aug 2025',
    followUpReason: 'ANC 2nd Checkup & Vitals',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'm002-0000-0000-0002',
    familyUnitId: 'f012-0000-0000-0012',
    name: 'Rajesh Verma',
    initials: 'RV',
    dob: '14/10/1989',
    age: 35,
    gender: 'Male',
    relationship: 'Self',
    phone: '9876500012',
    maritalStatus: 'Married',
    education: 'Graduate',
    isAbhaLinked: true,
    abhaNumber: '14-1234-5678-9013',
    isPregnant: false,
    hasChronicCondition: true,
    chronicConditionType: 'Hypertension',
    isNcdPatient: true,
    ncdDiagnosis: 'Hypertension',
    lastSurveyDate: '12 Aug 2025',
    followUpDueDate: '30 Sep 2025',
    followUpReason: 'BP Monitoring & Low Salt Diet',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'm003-0000-0000-0003',
    familyUnitId: 'f012-0000-0000-0012',
    name: 'Aarti Verma',
    initials: 'AV',
    dob: '05/01/2009',
    age: 16,
    gender: 'Female',
    relationship: 'Daughter',
    fatherOrHusbandName: 'Rajesh Verma',
    maritalStatus: 'Unmarried',
    education: 'High School',
    isAbhaLinked: false,
    isPregnant: false,
    hasChronicCondition: false,
    followUpDueDate: '25 Sep 2025',
    followUpReason: 'Immunization (Td)',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'm004-0000-0000-0004',
    familyUnitId: 'f012-0000-0000-0012',
    name: 'Vivek Verma',
    initials: 'VV',
    dob: '18/06/2015',
    age: 10,
    gender: 'Male',
    relationship: 'Son',
    fatherOrHusbandName: 'Rajesh Verma',
    education: 'Primary',
    isChild: true,
    isAbhaLinked: false,
    isPregnant: false,
    hasChronicCondition: false,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'm005-0000-0000-0005',
    familyUnitId: 'f012-0000-0000-0012',
    name: 'Pooja Verma',
    initials: 'PV',
    dob: '22/09/2024',
    age: 1,
    gender: 'Female',
    relationship: 'Daughter',
    fatherOrHusbandName: 'Rajesh Verma',
    isChild: true,
    isAbhaLinked: false,
    isPregnant: false,
    hasChronicCondition: false,
    followUpDueDate: '30 Sep 2025',
    followUpReason: 'Growth monitoring & MR-1',
    updatedAt: new Date().toISOString(),
  },

  // House 6: Shanti Devi (NCD Cancer Patient Line Listing)
  {
    id: 'm006-0000-0000-0001',
    familyUnitId: 'f006-0000-0000-0006',
    name: 'Shanti Devi',
    initials: 'SD',
    dob: '25/07/1968',
    age: 57,
    gender: 'Female',
    relationship: 'Self',
    phone: '9876500006',
    maritalStatus: 'Widow',
    education: 'Illiterate',
    isAbhaLinked: true,
    isPregnant: false,
    hasChronicCondition: true,
    chronicConditionType: 'Oral Cancer',
    isNcdPatient: true,
    ncdDiagnosis: 'Oral Cancer',
    lastSurveyDate: '08 Aug 2025',
    followUpDueDate: '15 Aug 2025',
    followUpReason: 'Chemotherapy follow-up & Pain assessment',
    updatedAt: new Date().toISOString(),
  },

  // House 14: Naresh Patel Family (Child Immunization: Aarav Patel)
  {
    id: 'm014-0000-0000-0001',
    familyUnitId: 'f014-0000-0000-0014',
    name: 'Naresh Patel',
    initials: 'NP',
    dob: '28/05/1992',
    age: 33,
    gender: 'Male',
    relationship: 'Self',
    phone: '9876500014',
    maritalStatus: 'Married',
    education: 'High School',
    isAbhaLinked: true,
    isPregnant: false,
    hasChronicCondition: false,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'm014-0000-0000-0002',
    familyUnitId: 'f014-0000-0000-0014',
    name: 'Kavita Patel',
    initials: 'KP',
    dob: '12/03/1996',
    age: 29,
    gender: 'Female',
    relationship: 'Wife',
    fatherOrHusbandName: 'Naresh Patel',
    phone: '9876500014',
    maritalStatus: 'Married',
    education: 'Middle',
    isAbhaLinked: true,
    isPregnant: false,
    hasChronicCondition: false,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'm014-0000-0000-0003',
    familyUnitId: 'f014-0000-0000-0014',
    name: 'Aarav Patel',
    initials: 'AP',
    dob: '10/05/2025',
    age: 3,
    gender: 'Male',
    relationship: 'Son',
    fatherOrHusbandName: 'Naresh Patel',
    isChild: true,
    isAbhaLinked: false,
    isPregnant: false,
    hasChronicCondition: false,
    lastSurveyDate: '13 Aug 2025',
    followUpDueDate: '28 Aug 2025',
    followUpReason: 'Pentavalent-3 & OPV-3 Due (14 Weeks)',
    updatedAt: new Date().toISOString(),
  },
];

/**
 * Official Child Immunization Registry (सर्वे प्रपत्र — टीकाकरण)
 */
export const SEED_CHILD_VACCINATIONS: ChildVaccinationRecord[] = [
  {
    id: 'vax-001',
    familyUnitId: 'f014-0000-0000-0014',
    childMemberId: 'm014-0000-0000-0003',
    childName: 'Aarav Patel',
    fatherName: 'Naresh Patel',
    gender: 'Male',
    dob: '10/05/2025',
    ageMonths: 3,
    phone: '9876500014',
    mctsCode: 'MCTS-UP-2025-0912',
    vaccines: {
      // Birth (जन्म के समय)
      BCG: 'Given',
      'OPV-0': 'Given',
      'Hepatitis-B-0': 'Given',
      // 6 Weeks (6 सप्ताह - 1½ माह)
      'OPV-1': 'Given',
      'Pentavalent-1': 'Given',
      'fIPV-1': 'Given',
      'Rotavirus-1': 'Given',
      'PCV-1': 'Given',
      // 10 Weeks (10 सप्ताह - 2½ माह)
      'OPV-2': 'Given',
      'Pentavalent-2': 'Given',
      'Rotavirus-2': 'Given',
      // 14 Weeks (14 सप्ताह - 3½ माह)
      'OPV-3': 'Due',
      'Pentavalent-3': 'Due',
      'Rotavirus-3': 'Due',
      'fIPV-2': 'Due',
      'PCV-2': 'Due',
      // 9-12 Months
      'MR-1': 'Not Given',
      'PCV Booster': 'Not Given',
      'JE-1': 'Not Given',
      'Vitamin-A 1': 'Not Given',
      // 16-24 Months
      'MR-2': 'Not Given',
      'JE-2': 'Not Given',
      'DPT Booster-1': 'Not Given',
      'OPV Booster': 'Not Given',
      // 5-6 Years
      'DPT Booster-2': 'Not Given',
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'vax-002',
    familyUnitId: 'f012-0000-0000-0012',
    childMemberId: 'm005-0000-0000-0005',
    childName: 'Pooja Verma',
    fatherName: 'Rajesh Verma',
    gender: 'Female',
    dob: '22/09/2024',
    ageMonths: 11,
    phone: '9876500012',
    mctsCode: 'MCTS-UP-2024-4481',
    vaccines: {
      BCG: 'Given',
      'OPV-0': 'Given',
      'Hepatitis-B-0': 'Given',
      'OPV-1': 'Given',
      'Pentavalent-1': 'Given',
      'fIPV-1': 'Given',
      'Rotavirus-1': 'Given',
      'PCV-1': 'Given',
      'OPV-2': 'Given',
      'Pentavalent-2': 'Given',
      'Rotavirus-2': 'Given',
      'OPV-3': 'Given',
      'Pentavalent-3': 'Given',
      'Rotavirus-3': 'Given',
      'fIPV-2': 'Given',
      'PCV-2': 'Given',
      'MR-1': 'Due',
      'PCV Booster': 'Due',
      'JE-1': 'Due',
      'Vitamin-A 1': 'Due',
      'MR-2': 'Not Given',
      'DPT Booster-1': 'Not Given',
      'DPT Booster-2': 'Not Given',
    },
    updatedAt: new Date().toISOString(),
  },
];

/**
 * ASHA Meetings Registry (आशा बैठकें व ग्राम स्वास्थ्य समिति)
 */
export const SEED_MEETINGS: AshaMeetingRecord[] = [
  {
    id: 'mtg-001',
    meetingDate: '15/08/2025',
    venue: 'ग्राम पंचायत भवन, चाँदपुर',
    meetingType: 'VHSNC',
    attendeesCount: 14,
    materialsAvailable: 'ग्राम स्वास्थ्य रजिस्टर, ओआरएस पैकेट, जिंक गोली, ब्लीचिंग पाउडर किट',
    discussionPoints: 'बरसात के मौसम में डायरिया रोकथाम, सुरक्षित पेयजल, नाली की सफाई एवं गर्भवती महिलाओं के संस्थागत प्रसव हेतु जागरूकता।',
    decisionsTaken: 'सभी हैंडपंप पर क्लोरिनेशन कराना एवं आगामी वीएचएनडी दिवस पर सभी 7-दिन वाले घरों को प्राथमिकता देना।',
    ashaWorkerPhone: '9876543210',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'mtg-002',
    meetingDate: '05/08/2025',
    venue: 'प्राथमिक स्वास्थ्य केन्द्र (PHC) चाँदपुर',
    meetingType: 'ASHA Cluster',
    attendeesCount: 22,
    materialsAvailable: 'एएनसी रिपोर्ट कार्ड, एचआरपी रजिस्टर, बीपी मॉनिटर, हीमोग्लोबिन मीटर',
    discussionPoints: 'अस्पताल से छूटे रेफरल मरीजों की ट्रैकिंग, उच्च रक्तचाप (Hypertension) स्क्रीनिंग एवं नियमित टीकाकरण कवरेज बढ़ाना।',
    decisionsTaken: 'छूटे हुए रेफरल मरीजों को 7 दिन के भीतर गृह भेंट कर रिपोर्ट एएनएम को देना।',
    ashaWorkerPhone: '9876543210',
    createdAt: new Date().toISOString(),
  },
];

/**
 * Survey Responses matching Government Registers (ANC 1 & ANC 2, NCD Line Listing)
 */
export const SEED_SURVEYS: SurveyResponse[] = [
  {
    id: 'srv-001',
    familyUnitId: 'f012-0000-0000-0012',
    familyMemberId: 'm001-0000-0000-0001',
    categoryCode: 'PREGNANCY',
    ashaWorkerPhone: '9876543210',
    answers: {
      // General ANC Information
      womanName: 'Suman Verma',
      husbandName: 'Rajesh Verma',
      womanAge: 28,
      ancLocation: 'ग्राम स्वास्थ्य एवं पोषण दिवस (VHND)',
      lmpDate: '12/01/2025',
      eddDate: '19/10/2025',
      firstTrimesterRegistered: 'Yes',
      folicAcidTablets: 30,
      isHrp: 'Yes',

      // ANC First Check (प्रथम जाँच)
      anc1Date: '10/04/2025',
      anc1TtDose: 'TT-1 Given',
      anc1Bp: '118/76',
      anc1Weight: 54.5,
      anc1Hb: 10.8,
      anc1Hiv: 'Negative / Normal',
      anc1AbdominalExam: 'Normal', // पेट की जाँच
      anc1UrineTest: 'Normal (No Albumin / Sugar)', // मूत्र जाँच
      anc1PregnancyStatus: 'Normal Growth',
      anc1IfaTablets: 60, // आयरन-फोलिक गोली
      anc1CalciumTablets: 60, // कैल्शियम गोली

      // ANC Second Check (द्वितीय जाँच)
      anc2Date: '12/08/2025',
      anc2TtDose: 'TT-2 Booster Given',
      anc2Bp: '122/80',
      anc2Weight: 58.0,
      anc2Hb: 10.4,
      anc2Hiv: 'Negative',
      anc2AbdominalExam: 'Normal',
      anc2UrineTest: 'Trace Sugar (Checked)',
      anc2IfaTablets: 60,
      anc2CalciumTablets: 60,
      anc2UltrasoundDone: 'Yes (PHC Centre)',
      remarks: '2nd Trimester ANC completed. Counseled on institutional delivery at PHC and daily IFA + Calcium.',
    },
    voiceNotes: 'सुमन वर्मा का द्वितीय प्रसवपूर्व चेकअप पूर्ण हुआ। टीटी-2 बूस्टर दिया गया, वजन 58 किलो और हीमोग्लोबिन 10.4 ग्राम है। कैल्शियम और आयरन की 60 गोलियां दी गईं।',
    syncedToAnm: false,
    createdAt: '2025-08-12T10:30:00.000Z',
  },
  {
    id: 'srv-002',
    familyUnitId: 'f012-0000-0000-0012',
    familyMemberId: 'm002-0000-0000-0002',
    categoryCode: 'DISEASE',
    ashaWorkerPhone: '9876543210',
    answers: {
      patientName: 'Rajesh Verma',
      diagnosis: 'Hypertension',
      diagnosisDate: '14/03/2024',
      symptoms: 'Occasional Headache, Dizziness on heavy work',
      referredTo: 'PHC Chandpur',
      treatmentStarted: 'Yes',
      treatmentStatus: 'उपचार जारी (Treatment Ongoing)',
      bpSystolic: 142,
      bpDiastolic: 92,
      onRegularMedication: 'Yes (Amlodipine 5mg)',
      dietSaltReduced: 'Yes',
      surveyFormFilledByAsha: 'Yes',
      remarks: 'Hypertension follow-up: BP 142/92. Counseled on low salt diet and regular daily medication.',
    },
    voiceNotes: 'राजेश वर्मा का बीपी 142 बटे 92 है। दवा नियमित ले रहे हैं। नमक कम खाने को कहा।',
    syncedToAnm: false,
    createdAt: '2025-08-12T11:15:00.000Z',
  },
  // NCD Cancer Line Listing for Shanti Devi (House 6)
  {
    id: 'srv-003',
    familyUnitId: 'f006-0000-0000-0006',
    familyMemberId: 'm006-0000-0000-0001',
    categoryCode: 'DISEASE',
    ashaWorkerPhone: '9876543210',
    answers: {
      patientName: 'Shanti Devi',
      diagnosis: 'Oral Cancer (मुख का कैंसर)',
      diagnosisDate: '10/01/2025',
      symptoms: 'Non-healing white patch and ulcer in mouth, difficulty in swallowing',
      referredTo: 'District Hospital / Cancer Institute',
      treatmentStarted: 'Yes',
      treatmentStatus: 'उपचार जारी (Treatment Ongoing)',
      postTreatmentCondition: 'सुधार जारी (Treatment Ongoing)',
      surveyFormFilledByAsha: 'Yes',
      remarks: 'Referred to District Hospital for chemo cycle. ASHA home visits regular.',
    },
    voiceNotes: 'शांति देवी मुख के कैंसर से ग्रसित हैं। जिला अस्पताल से कीमोथेरेपी चल रही है। आशा द्वारा निरंतर फॉलो-अप जारी है।',
    syncedToAnm: false,
    createdAt: '2025-08-08T09:40:00.000Z',
  },
];

export const SEED_FOLLOWUPS: FollowUpTask[] = [
  {
    id: 'tsk-001',
    familyUnitId: 'f012-0000-0000-0012',
    familyMemberId: 'm001-0000-0000-0001',
    initials: 'SV',
    name: 'Suman Verma',
    taskType: 'ANC 2nd Checkup & Vitals',
    dueDate: 'Due: 19 Sep 2025',
    urgencyDays: '2 days',
    isCompleted: false,
    ashaWorkerPhone: '9876543210',
  },
  {
    id: 'tsk-002',
    familyUnitId: 'f014-0000-0000-0014',
    familyMemberId: 'm014-0000-0000-0003',
    initials: 'AP',
    name: 'Aarav Patel',
    taskType: 'Pentavalent-3 & OPV-3 Vaccination',
    dueDate: 'Due: 28 Aug 2025',
    urgencyDays: '5 days',
    isCompleted: false,
    ashaWorkerPhone: '9876543210',
  },
  {
    id: 'tsk-003',
    familyUnitId: 'f012-0000-0000-0012',
    familyMemberId: 'm002-0000-0000-0002',
    initials: 'RV',
    name: 'Rajesh Verma',
    taskType: 'BP check & NCD Follow-up',
    dueDate: 'Due: 30 Sep 2025',
    urgencyDays: '10 days',
    isCompleted: false,
    ashaWorkerPhone: '9876543210',
  },
  {
    id: 'tsk-004',
    familyUnitId: 'f006-0000-0000-0006',
    familyMemberId: 'm006-0000-0000-0001',
    initials: 'SD',
    name: 'Shanti Devi',
    taskType: 'Oral Cancer Follow-up Visit',
    dueDate: 'Due: 15 Sep 2025',
    urgencyDays: '7 days',
    isCompleted: false,
    ashaWorkerPhone: '9876543210',
  },
];
